# Generated by Django 3.2.7 on 2021-09-07 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_aut', models.FloatField(default=0.0)),
                ('relation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namecat', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_wr', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=64)),
                ('post_text', models.TextField()),
                ('field_choise', models.CharField(choices=[('AR', 'статья'), ('NW', 'новость')], default='AR', max_length=2)),
                ('rating_post', models.FloatField(default=0.0)),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Newapp.author')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Newapp.category')),
                ('rel_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Newapp.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_category',
            field=models.ManyToManyField(through='Newapp.PostCategory', to='Newapp.Category'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_text', models.CharField(max_length=124)),
                ('time_comm', models.DateTimeField(auto_now_add=True)),
                ('rating_comm', models.FloatField(default=0.0)),
                ('post_comm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Newapp.post')),
                ('user_comm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
